on: push

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 5

    name: Build and test the project, using VS2019

    steps:
    - name: checkout the Lab repo
      uses: actions/checkout@v2
      with:
        path: lab

    - name: checkout the grader-tools repo
      uses: actions/checkout@v2
      with:
        repository: av-pavlov/grader-tools
        ref: master
        path: tools

    - name: Build the project
      run: |
        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include;%GITHUB_WORKSPACE%\tools
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        echo on
        for /F "usebackq" %%i in ('${{github.workflow}}') do set TASKNO=%%~ni 
        echo ПЕРЕХОЖУ В ПАПКУ %GITHUB_WORKSPACE%\lab\%TASKNO%
        cd %GITHUB_WORKSPACE%\lab\%TASKNO%
        rmdir /S /Q Debug
        set DefaultPlatformToolset=v142
        set VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\
        set MSBUILD="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
        %GITHUB_WORKSPACE%\tools\build.cmd
        grep
      shell: cmd
