name: Test Visual Studio Build

on: [push]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      fail-fast: false
    timeout-minutes: 30

    name: Python ${{ matrix.python-version }} ${{ matrix.architecture }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: MikeMirzayanov/testlib
        ref: master

    - name: Build the solution
      run: |
        REM FIXME uses /MT not /MD, see makefile.vc and win32.mak for more info
        echo on
        set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\V7.1A\Include;%GITHUB_WORKSPACE%\testlib
        set INCLIB=%GITHUB_WORKSPACE%\testlib
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.platform-vcvars }}
        cd %GITHUB_WORKSPACE
        rmdir /S /Q objs
        set DefaultPlatformToolset=v142
        set VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\
        set MSBUILD="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
        %MSBUILD% /t:rebuild /p:Configuration=Debug /p:PlatformToolset=%DefaultPlatformToolset% /m
      shell: cmd

